<a href="https://colab.research.google.com/github/KseniyaIvanovaG/Pyton/blob/main/Lesson1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Тема “Вычисления с помощью Numpy”

Импортируем библиотеку Numpy

In [39]:
import numpy as np

Создаем массив

In [40]:
a = np.array([[1, 6],
             [2, 8],
             [3, 11],
             [3, 10],
             [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

Находим среднее значение по каждому признаку

In [41]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

Вычисляем массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a

In [42]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Чтобы найти скалярное произведение столбцов массива a_centered сначала выводим каждый столбец отдельно

In [43]:
c = a_centered[0:, 0]
c


array([-1.,  0.,  1.,  1., -1.])

In [44]:
d = a_centered[0:, 1]
d

array([-2.4, -0.4,  2.6,  1.6, -1.4])

А теперь находим их скалярное произведение

In [45]:
a_centered_sp = c.dot(d)
a_centered_sp

8.0

Так как изначально было дано, что число наблюдений это число строк, находим число строк массива

In [46]:
N, O = a_centered.shape
N

5

Делим a_centered_sp на N-1, где N - число наблюдений

In [47]:
cov = a_centered_sp / (N-1)
cov

2.0

Проверяем получившееся число, вычислив ковариацию с помощью функции np.cov

In [48]:
np.cov(np.transpose(a))

array([[1. , 2. ],
       [2. , 4.3]])

## Тема “Работа с данными в Pandas”

Импортируем библиотеку Pandas

In [49]:
import pandas as pd

Создаем датафрейм authors

In [50]:
a = {
    'author_id': [1, 2, 3],
    'author_name': ['Тургенев', 'Чехов', 'Островский']
}
authors = pd.DataFrame(a)
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

Создаем датафрейм book

In [51]:
b = {
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price': [450, 300, 350, 500, 450, 370, 290]
}
book = pd.DataFrame(b)
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

Получаем датафрейм authors_price, соединив датафреймы authors и books по полю author_id

In [52]:
authors_price = pd.merge(authors, book, on='author_id', how='outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

Сначала отсортируем таблицу по столбцу цена в порядке убывания

In [53]:
sorted_authors_price = authors_price.sort_values(by='price', ascending=False)
sorted_authors_price


author_id author_name            book_title  price
3          2       Чехов      Толстый и тонкий    500
0          1    Тургенев           Отцы и дети    450
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
2          1    Тургенев     Дворянское гнездо    350
1          1    Тургенев                 Рудин    300
6          3  Островский  Таланты и поклонники    290

Теперь создаем датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами

In [54]:
top5 = sorted_authors_price.head(5)
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

Сгруппируем авторов из датафрейма

In [55]:
group_authors = authors_price.groupby('author_name')
group_authors

Создадим датафреймы с минимальной, максимальной ценой и средним значением цены

In [56]:
min_price = group_authors.agg({'price': "min"}).rename(columns={'price':'min_price'})
min_price

min_price
author_name           
Островский         290
Тургенев           300
Чехов              450

In [57]:
max_price = group_authors.agg({'price': "max"}).rename(columns={'price':'max_price'})
max_price

max_price
author_name           
Островский         370
Тургенев           450
Чехов              500

In [58]:
mean_price = group_authors.agg({'price': "mean"}).rename(columns={'price':'mean_price'})
mean_price

mean_price
author_name            
Островский   330.000000
Тургенев     366.666667
Чехов        475.000000

Объединяем датафреймы

In [61]:
authors_stat = pd.concat([min_price, max_price, mean_price], axis=1)
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

Добавим новый столбец в датафрейм authors_price

In [64]:
authors_price["cover"] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price quantity    cover
0          1    Тургенев           Отцы и дети    450  твердая  твердая
1          1    Тургенев                 Рудин    300   мягкая   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая  твердая
4          2       Чехов       Дама с собачкой    450  твердая  твердая
5          3  Островский                 Гроза    370   мягкая   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая   мягкая

Для каждого автора считаем суммарную стоимость книг в твердой и мягкой обложке

In [65]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'],
                    columns=['cover'], aggfunc=np.sum, fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

Сохраним полученный датафрейм в формат pickle

In [66]:
book_info.to_pickle('book_info.pkl')

Затем загружаем из этого файла датафрейм и называем его book_info2

In [67]:
book_info2 = pd.read_pickle('book_info.pkl')

Убеждаемся, что датафреймы идентичны

In [68]:
book_info==book_info2

cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев       True     True
Чехов          True     True